CREATE TABLE  PollList (
    NUM         NUMBER      PRIMARY KEY,
    QUESTION    VARCHAR2(200),
    SDATE       DATE,
    EDATE       DATE,
    WDATE       DATE,
    TYPE        NUMBER      DEFAULT 1,
    ACTIVE      NUMBER      DEFAULT 1
);

CREATE TABLE  PollItem(
    LISTNUM     NUMBER      NOT NULL,
    ITEMNUM     NUMBER      DEFAULT 0 NOT NULL,
    ITEM        VARCHAR2(50)DEFAULT '',
    COUNT       NUMBER      DEFAULT 0 ,
    PRIMARY KEY(LISTNUM,ITEMNUM)
);

CREATE SEQUENCE POLL_SEQ START WITH 1 INCREMENT BY 1;