CREATE TABLE MEMBER (
MEM_ID VARCHAR2(20) PRIMARY KEY,
MEM_PWD VARCHAR2(20),
MEM_NAME VARCHAR2(20),
GENDER CHAR(1),
BIRTHDAY CHAR(6),
EMAIL VARCHAR2(30),
ZIPCODE CHAR(5),
ADDRESS VARCHAR2(60),
DETAILADDRESS VARCHAR2(20),
HOBBY CHAR(5),
JOB VARCHAR2(30)
)